version: "3.8"

services:
  project:
    build: ../Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../uploads:/app/uploads
  postgresql:
    image: postgres
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:Z,ro
    restart: always
    env_file:
      - ./postgres.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: aliAghapour
      MINIO_ROOT_PASSWORD: al!@Aghap0ur
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}
